### ISSUE TITLE
SSLError: Certificate verifty failed

### ISSUE THREAD

**Issue by yas18** [EnergieID/entsoe-py#117]
Hello,

I can not ran any query because im facing  authentification issues;

SSLError: HTTPSConnectionPool(host='transparency.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A75&processType=A16&in_Domain=10YFR-RTE------C&securityToken=4b6584a7-25a0-41b5-bdaf-5a7bf1a691e3&periodStart=202012312300&periodEnd=202101012300 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))

**Comment by jpaduart** [comment]
This has nothing to do with the entsoe-py package, could be proxy related (Zscaler, etc.). Try to figure out your company's proxy settings and do something like:

PROXIES = {"http":"http://123.45.67.89:8080", "https":"https://123.45.67.89:8080"}
TOKEN = "XXX"

CONN = entsoe.EntsoePandasClient(api_key = TOKEN, proxies = PROXIES)

**Comment by paolonervosi** [comment]
I have the same issue. 

When running:

`proxies = {
 "http": "http://xx.xx.xx.xx:xxx",
 "https": "http://xx.xx.xx.xx:xx",
}
client = EntsoePandasClient(api_key="xxx", proxies=proxies)
df = client.query_generation(i, start=start,end=end, psr_type=None).tz_convert('Europe/Rome').tz_localize(None)`

i get this error:

ProxyError: HTTPSConnectionPool(host='transparency.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A75&processType=A16&in_Domain=10YAT-APG------L&securityToken=xxxx&periodStart=201912312300&periodEnd=202001012300 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None)))

**Comment by FrankBoermanTenneT** [comment]
> I have the same issue.
> 
> When running:
> 
> `proxies = { "http": "http://xx.xx.xx.xx:xxx", "https": "http://xx.xx.xx.xx:xx", } client = EntsoePandasClient(api_key="xxx", proxies=proxies) df = client.query_generation(i, start=start,end=end, psr_type=None).tz_convert('Europe/Rome').tz_localize(None)`
> 
> i get this error:
> 
> ProxyError: HTTPSConnectionPool(host='transparency.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A75&processType=A16&in_Domain=10YAT-APG------L&securityToken=xxxx&periodStart=201912312300&periodEnd=202001012300 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None)))

and @jpaduart is right, this again is not an issue for this library. You have a general issue with connecting to your proxy. Make sure the settings and auth to your proxy is correct.

you can also try to set environment variables instead of the proxies dictionary like so: https://github.com/EnergieID/entsoe-py/issues/122#issuecomment-895066770
