### ISSUE TITLE
No day-ahead prices for IE

### ISSUE THREAD

**Issue by Tomkourou** [EnergieID/entsoe-py#145]
Hi, 

thanks for the great package! I have been trying to get day ahead prices for Ireland to no avail. I suspect its a problem on the API side but I am posting it here just in case: 

```
import pandas as pd
from entsoe import EntsoePandasClient 

key = open(r"apiKey.txt").read()
client = EntsoePandasClient(api_key=key)


start_date = '20210101'
end_date = '20210125'
start = pd.Timestamp(start_date,tz='Europe/Dublin')
end= pd.Timestamp(end_date,tz='Europe/Dublin')
print(start,end)

client.query_day_ahead_prices("IE",start= start,end=end)

```
Returns an empty series but there is data available on the API. Other countries work as expected. 

Many thanks, 

Tom

**Comment by fboerman** [comment]
hi @Tomkourou this is because you are using IE which maps to the country in general. I am not sure where the distinction is used but it is pulled from the [entsoe docs](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html) at the bottom.

you will want to use ```IE_SEM``` then you get the actual bidding zone. you can see it in the mapping here: https://github.com/EnergieID/entsoe-py/blob/master/entsoe/mappings.py#L76

I tried your code with this and then it works! let me know if you run into other issues. For now im going to close this issue.
