### ISSUE TITLE
Unmarked currency changes

### ISSUE THREAD

**Issue by Tomkourou** [EnergieID/entsoe-py#153]
I have noticed that in price data there are instances where ENTSOE changes the unit currency. For example, for Poland the ENTSOE website states the following: 

"_Please note that due to distinct market arrangements for certain periods Day-ahead Prices are expressed in different currencies:
From 5 January 2015 Day-ahead Prices for the Polish Area are expressed in **EUR/MWh.**
Between 2 March 2017 and 19 November 2019 Day-ahead Prices are published in **PLN/MWh**.
Starting from 20 November 2019 Day-ahead Prices are equal to fixed auction prices from the Single Day-ahead Coupling in **EUR/MWh.**_ "

When one pulls historical data like day-ahead prices this change in currency will not be immediately obvious as the currency is not displayed. Would it be possible to add a column in the pandas client showing the currency?

**Comment by fboerman** [comment]
hi @Tomkourou I dont think the api returns this info so then we need to put hardcoded rules into place.

I dont have the time to fully investigate this now, if you can provide a pull request I will look at it.

**Comment by MattEwen** [comment]
@fboerman Just bumping this - the currency is provided as an attribute of `<TimeSeries>` so could be grabbed. I'd be happy to have a go implementing this when I get time. However it would mean returning a df instead of a series which I imagine could make a lot of people's code fail. Is this an ok change, or would it be better in a new query method for the time being?

**Comment by jpaduart** [comment]
I would say it's overkill to include the currency into the existing
Series/Dataframes, accompanying the prices, because in my experience, only
Poland and Romania exhibit currency changes.
It would break the code, plus be discarded by most users anyway.
A (new) specific query looks like the best solution to me.


Op vr 13 mei 2022 om 07:58 schreef Matt Ewen ***@***.***>:

**Comment by fboerman** [comment]
hi @MattEwen and @jpaduart I agree that breaking the functionality from series to dataframe is not something we would want.

@jpaduart what you are saying is not entirely true. There are specific timeperiods when more countries had different currencies and poland even swapped twice back and forth as said in the OP.

@MattEwen I think best would be to have an extra function called ```query_day_ahead_prices_with_currencies``` or something similar. It would be great if you could do this with a PR!

**Comment by MattEwen** [comment]
hi @fboerman - just wanted to check in and apologise for not getting to this. We've changed to a different approach for price data so unfortunately I don't think I'll be able to

**Comment by fboerman** [comment]
hi @MattEwen no problem, but im gonna close this issue for now since I dont think its that important to fix
