### ISSUE TITLE
Time interval 

### ISSUE THREAD

**Issue by AbdouMechraoui** [EnergieID/entsoe-py#27]
Hello,
I really appreciate the effort has been put towards making this package it's just saved me a lot of time. For some reason the time interval described in the documentation is returning the same values when I do not use the time interval. For example: 

    start = pd.Timestamp('2019-06-22 12:12:00', tz='Europe/Zurich')
    end = pd.Timestamp('2019-06-23 12:12:00', tz='Europe/Zurich')
    country_code = 'CH'  # swiss
    pandaDp=client2.query_day_ahead_prices(country_code, start=start, end=end)

the resulting list I get from this piece of code is exactly the same when I don't use the hour.

    start = pd.Timestamp('2019-06-22', tz='Europe/Zurich')
    end = pd.Timestamp('2019-06-23', tz='Europe/Zurich')
    country_code = 'CH'  # swiss
    pandaDp=client2.query_day_ahead_prices(country_code, start=start, end=end)

I would like to get the values from one specific hour to the next specific hour. However, I am just getting the same exact thing which the values from 00:00 to 00:00 the next day. Am I missing anything? Once again thanks a lot

**Comment by JrtPec** [comment]
Hi,

This is - somewhat - expected behaviour: the Entso-e API only accepts timestamps that are rounded to midnight, and returns the entire day.

You can off course truncate this in pandas:

```df = df.truncate(before=start, after=end)```

It would be cleanest to add that line to all methods in the Pandas Client, so I'll leave this issue open until somebody does the effort to add a pull request for it.
