### ISSUE TITLE
AttributeError Query for contracted reserve amount and contracted reserve prices not working

### ISSUE THREAD

**Issue by brunolehner** [EnergieID/entsoe-py#370]
Hi, 
I tried to use the query to get the contracted reserve amount and contracted reserve prices for Austria in 2023. 
But unfortunately it is not working. I used the following code: 

`# load packages
from entsoe import EntsoeRawClient
import pandas as pd`

`client = EntsoeRawClient(api_key='XY')`

`start = pd.Timestamp('20230101', tz='Europe/Vienna')
end = pd.Timestamp('20231231', tz='Europe/Vienna')
country_code = 'AT'  # Austria
type_marketagreement_type = 'A01'`

`client.query_contracted_reserve_amount(country_code, type_marketagreement_type, start, end, psr_type=None)`
`client.query_contracted_reserve_prices(country_code, type_marketagreement_type, start=start, end=end, psr_type=None)`

I get: 

- AttributeError: 'str' object has no attribute 'tzinfo'

- TypeError: EntsoeRawClient.query_contracted_reserve_prices() got multiple values for argument 'start'

Can someone help me out?

**Comment by fboerman** [comment]
Hi some remarks:
* Please hide your api key
* please use explicit arguments so start= etc

⁣Get BlueMail for Android ​

**Comment by brunolehner** [comment]
Hi, 
I tried using explicit arguements, e.g.: 
`client.query_contracted_reserve_amount(country_code = 'AT', type_marketagreement_type = 'A01', 
start = pd.Timestamp('20230101', tz='Europe/Vienna'), end = pd.Timestamp('20231231', tz='Europe/Vienna'), 
psr_type=None)`

Now I get "NoMatchingDataError" 

Is there no data for Austria in 2023 available?

**Comment by fboerman** [comment]
hi did you check if there is data on the UI for the dates you are requesting?

**Comment by christianfosli** [comment]
I'm not an expert but thought I'd chime in as I struggled with something similar:

These two endpoints are marked as "legacy" in the Entsoe UI, and replaced by "Volumes and Prices of Contracted Reserves". For the cases I tested for NO2 the legacy endpoints do not return any data, but `query_contracted_reserve_prices_procured_capacity` does!

Note that currently it seems we need to use the Raw client instead of the Pandas client if we need volumes in addition to prices though (see my issue #374)

**Comment by fboerman** [comment]
ah yes you are correct @christianfosli I need to fix this in #374 (or if somebody wants to help feel free to open a PR!)
