### ISSUE TITLE
Download of imbalance prices has stopped working

### ISSUE THREAD

**Issue by popeze** [EnergieID/entsoe-py#47]
Download of imbalance prices has stopped working, it is very likely because API request for imbalance prices now returns ZIP file, whereas API request for day ahead prices (which still works) returns directly XML data.

**Comment by wbworks** [comment]
I contacted entsoe-e to get information whether this is the intented behaviour - and yes it is:

"Thank you for your reporting the issue. At the beginning of February 2020, API response for mentioned data items have been changed to zip format, in order to be able to respond queries that have **different docStatus type** within the queried time interval. Because, with a single xml file, it is not possible to response for various docStatus. API guide will be improved for accordingly with latest changes, apologies for the inconvenience caused." (Mar 13, 11:44 CET)

**Comment by JrtPec** [comment]
This will be fixed in version 0.3.0
