### ISSUE TITLE
Query cross-border flows (enhancement)

### ISSUE THREAD

**Issue by fgenoese** [EnergieID/entsoe-py#5]
Very useful tool, congratulations to the team.

I see that currently one cannot query the cross-border flows, e.g.:
https://transparency.entsoe.eu/transmission-domain/physicalFlow/show

Do you plan to add this in a future release?

**Comment by JrtPec** [comment]
Hi, thanks!

There is no real "roadmap" or "plan" for this package, I just add code that I find useful for my own projects. I guess the other contributors feel the same way.

At this moment I have no plans of my own for adding the cross-border flows, but I'm very happy to review and approve any pull request that you, or someone else sends my way!

If the cross-border-flow-requests are similar to the other ones, it shouldn't be hard at all to add them in. (If I feel like it, I might include it when I'm reviewing the next pull request)

**Comment by fgenoese** [comment]
Thanks, it was indeed quite straightforward. I created a pull request:
https://github.com/EnergieID/entsoe-py/pull/6

**Comment by RaquelVasquez** [comment]
Hello, thank you for the very useful code.

I have been using the cross-border flow query for all Germany and even though most of the data is retrieved successfully, I found that the data for the borders with two countries (CZ and DK) is completely different from the one published in ENTSO-E for both directions (2016 and 2017). Also, for the rest of the borders most of the flows are the same as published but there are some patterns here and there that differ. 

Have you experienced/noticed this issue? Could it be related to the parsers not working well?

Thank you!

**Comment by JrtPec** [comment]
I did notice some weird things!

Turns out the from/to countries were switched up.
So now (version 0.1.17) it is: `domain_in = country_code_to` and vice versa. Which makes sense to me. @fgenoese please look out that it doesn't break your code.

When working with Germany, you should also look at what domain to use, there is 'DE' (10Y1001A1001A83F), but also 'DE-AT-LU' (10Y1001A1001A63L) and a new 'DE-LU' is also being introduced. So it's best to double check, and let me know if changes are in order.

I have found this on [], concerning a 'DE-AT-LU' bidding zone split that is coming up:

> Dear Users,
>
>Please be informed, that we will start preparation of the platform for DE-AT-LU bidding zone split on >the 23rd of August. BZN|DE-AT-LU will be separated into 2 new bidding zones BZN|DE-LU and >BZN|AT.
> 
>New bidding zones will be active from the 1st of October, however, first data submissions, like month >ahead forecasts, are expected from the 1st of September. 
> 
>Validity end date for BZN|DE-AT-LU is the end of September 2018. 
> 
>EIC codes for new bidding zones:
>BZN|DE-LU - 10Y1001A1001A82H 
>BZN|AT - 10YAT-APG------L (same as control area or country)
> 
>Thanks for your patience and understanding.
> 
>Best Regards
>Transparency Platform Team.

I'm creating an issue to follow up on this.
