### ISSUE TITLE
Making another request - EntsoePandasClient

### ISSUE THREAD

**Issue by Gabriele1990** [EnergieID/entsoe-py#59]
Is it possible to make another requested not included in that listed by  EntsoePandasClient?

for what i can see, using EntsoeRawClient is possible to Making another request if the API-call I want is not in the list, instead i do not find the same thing for EntsoePandasClient.

thanks in advance.

Gabriele

**Comment by JrtPec** [comment]
That's not as easy as it sounds...

There are some API-methods that entsoe-py doesn't have support for (yet), but as you've already seen you can just input the parameters for that request and view the raw response from the API. That response can be in XML, Zip...

If you want to get that response in a Pandas Frame, you'd have to write a parser that converts the XML or Zip to Pandas. These parsers can get pretty specific, there is no one-size-fits-all.

So a better approach would be to open an issue specifically for the API request you'd like. (But also check the code again, a few methods have been added since you opened this issue)

good luck.
